# Generated by Django 2.1.7 on 2019-03-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, upload_to='pictures')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uploaded_by', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(editable=False, upload_to='thumbnails')),
            ],
        ),
    ]
